# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Sofia Leung
tagline:          
description:      'academic librarian. I like cats, whiskey, books, feminism, and libraries, duh. she/her/hers <a href="https://twitter.com/sofiayleung" target="_blank">@sofiayleung</a>.'
url:              http://sofialeu.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
